#!/bin/bash
#!/usr/bin/env bash
set -euo pipefail
# home="$(realpath "$(realpath "${BASH_SOURCE[0]}" | xargs dirname)"/.)"
# cd "$home"

# Ensure apt is set up to work with https sources:
sudo apt install apt-transport-https

wget -qO - https://download.sublimetext.com/sublimehq-pub.gpg | sudo apt-key add -
echo "deb https://download.sublimetext.com/ apt/stable/" | sudo tee /etc/apt/sources.list.d/sublime-text.list
# echo "deb https://download.sublimetext.com/ apt/dev/" | sudo tee /etc/apt/sources.list.d/sublime-text.list
sudo apt update
sudo apt install sublime-merge


